{% set name = "pygenutils" %}
{% set version = "15.13.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=68.0
    - wheel
  run:
    - python >=3.10
    - pip
    # Core dependencies available in conda channels
    - numpy >=1.21.0,<2.0.0
    - pandas >=1.3.0,<2.0.0
    # Note: more_itertools, filewise and paramlib will be installed via pip during post-link

test:
  imports:
    - pygenutils
    - pygenutils.arrays_and_lists
    - pygenutils.audio_and_video
    - pygenutils.dictionaries
    - pygenutils.number_bases
    - pygenutils.operative_systems
    - pygenutils.sets_and_intervals
    - pygenutils.strings
    - pygenutils.time_handling

about:
  home: https://github.com/EusDancerDev/pygenutils
  license: MIT
  license_file: LICENSE
  summary: A comprehensive Python utility library for general-purpose and specialised tasks
  description: |
    pygenutils is a comprehensive Python utilities package designed to provide a wide range of 
    general-purpose tools for data manipulation, string handling, time operations, and system interactions.
    It serves as a collection of commonly needed utilities for Python development.
  doc_url: https://github.com/EusDancerDev/pygenutils#readme
  dev_url: https://github.com/EusDancerDev/pygenutils.git

extra:
  recipe-maintainers:
    - EusDancerDev 